messages:
  responses:
    start: старт
    account: аккаунт
  errors:
    undefinedCommand: Такой команды не существует
  buttons:
    account: "💼 Личный кабинет"
    current_order: "📋 Текущий заказ"
  alert:
    undefinedButton: "Данная кнопка ещё не реализована"