messages:
  responses:
    start: старт

    account: "🔒*Личный кабинет*\n\n🚀Статус торговли: %s"
    off_trade: 🔴
    on_trade: 🟢

    warnings: "\n\n⚠️Предупреждение:\n%s"
    no_api_keys: "_Добавьте_ *все* _ключи для старта торговли_"
    no_success: "Один из ключей введён неверно или не имеет доступа к торговли!"

    new_user: новый пользователь
    add_api: Отправьте свой api_key
    add_secret: Отправьте свой secret_key
    delete_key: Для подтверждение удаления ключа нажмите кнопку "Подтверждаю 🚮"
    report: Отчёт об успехов бота с вашими средствами
    change_strategy: Выберите стратегию из списка ниже



  errors:
    undefinedCommand: Такой команды не существует
  buttons:
    account: "💼 Личный кабинет"

    change_strategy: "🔄 Сменить стратегию"

    on_trade: "🟢 Включить торговлю"
    off_trade: "🔴 Выключить торговлю"

    api_keys: "🔑 Настроить ключи"
    api_key_empty: "➕ Добавить API_KEY"
    secret_key_empty: "➕ Добавить SECRET_KEY"
    api_key_ready: "❌ Удалить API_KEY"
    secret_key_ready: "❌ Удалить SECRET_KEY"

    back: "↩ Вернуться"
    previous: "⬅️"
    next: "➡️"

    report: "📊 Отчёт о торговле"

    accept: "Подтверждаю 🚮"

  alert:
    undefinedButton: "Данная кнопка ещё не реализована"
    noStrategy: "Вы ещё не выбрали стратегию"
    failedOff: "Ошибка выключения"

time_sleep: 10
test_net: true