messages:
  responses:
    start: старт
    account: аккаунт
    new_user: новый пользователь
    add_api: отправьте свой api_key
    add_secret: отправьте свой secret_key
    delete_key: Для подтверждение удаления ключа нажмите кнопку "Подтверждаю 🚮"
    report: Отчёт об успехов бота с вашими средствами
    change_strategy: Выберите стратегию из списка ниже

  errors:
    undefinedCommand: Такой команды не существует
  buttons:
    account: "💼 Личный кабинет"

    change_strategy: "🔄 Сменить стратегию"

    on_trade: "🟢 Включить торговлю"
    off_trade: "🔴 Выключить торговлю"

    api_keys: "🔑 Настроить ключи"
    api_key_empty: "➕ Добавить API_KEY"
    secret_key_empty: "➕ Добавить SECRET_KEY"
    api_key_ready: "❌ Удалить API_KEY"
    secret_key_ready: "❌ Удалить SECRET_KEY"

    back: "↩ Вернуться"
    previous: "⬅️"
    next: "➡️"

    report: "📊 Отчёт о торговле"

    accept: "Подтверждаю 🚮"

    

  alert:
    undefinedButton: "Данная кнопка ещё не реализована"
    noStrategy: "Вы ещё не выбрали стратегию"
    failedOff: "Ошибка выключения"