DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS historyData CASCADE;
DROP TABLE IF EXISTS tradeStrategy CASCADE;